name: Bug report
description: Create a report to help us improve and investigate the issue
title: "[Bug] "
labels: bug
body:
  - type: input
    id: app-title
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: stepstoreproducebug
    attributes:
      label: Steps to reproduce the behavior
      value: |
        - 1. Go to '...'
        - 2. Click on '....'
        - 3. Scroll down to '....'
        - 4. See error
    validations:
      required: true

  - type: textarea
    id: upload-screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Upload your screenshots here
    validations:
      required: false

  - type: textarea
    id: phonespecs
    attributes:
      label: Smartphone (please complete the following information)
      value: |
        - Device: [e.g. Pixel 32 Pro]
        - OS: [e.g. OneUI 21]
        - Version [e.g. v2.1.0]
    validations:
      required: true

  - type: textarea
    id: extracontext
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
